export const MOCK_USER = {
  id: 'user-1',
  email: 'imran@nileuniversity.edu.ng',
};

export const MOCK_PROFILE = {
  id: 'user-1',
  email: 'imran@nileuniversity.edu.ng',
  full_name: 'Imran Adebayo',
  phone_number: '08012345678',
  course: 'Computer Science',
  campus_status: 'resident',
  hostel: 'Nile Hall A',
  terms_accepted: true,
  onboarding_complete: true,
  is_admin: true,
  is_courier: true,
  is_blacklisted: false,
  wallet_balance: 15000,
  total_earnings: 8500,
  pro_subscriber: false,
};

export const MOCK_ORDERS = [
  {
    id: 'order-1',
    buyer_id: 'user-1',
    order_type: 'purchase',
    pickup_location: 'Food Court',
    dropoff_location: 'Nile Hall A',
    status: 'on_the_way',
    items: [{ name: 'Jollof Rice', qty: 1, price: '1500' }, { name: 'Chicken', qty: 1, price: '800' }],
    food_cost: 2300,
    delivery_fee: 300,
    service_fee: 100,
    total_amount: 2700,
    delivery_code: '4782',
    courier_name: 'Ahmed Musa',
    courier_accepted: true,
    special_instructions: null,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-2',
    buyer_id: 'user-1',
    order_type: 'errand',
    pickup_location: 'Admin Block',
    dropoff_location: 'Nile Hall B',
    status: 'delivered',
    items: [],
    item_description: 'Course registration form',
    food_cost: 0,
    delivery_fee: 400,
    service_fee: 100,
    total_amount: 500,
    delivery_code: '1234',
    courier_name: 'Fatima Ibrahim',
    courier_accepted: true,
    special_instructions: null,
    delivered_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-3',
    buyer_id: 'user-1',
    order_type: 'purchase',
    pickup_location: 'Female Shopping Complex',
    dropoff_location: 'Nile Hall C',
    status: 'placed',
    items: [{ name: 'Chicken Shawarma', qty: 2, price: '1200' }],
    food_cost: 2400,
    delivery_fee: 300,
    service_fee: 100,
    total_amount: 2800,
    delivery_code: '5619',
    courier_name: null,
    courier_accepted: false,
    special_instructions: 'Extra sauce please',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: 'tx-1',
    user_id: 'user-1',
    type: 'topup',
    amount: 20000,
    balance_after: 15000,
    description: 'Wallet top up',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-2',
    user_id: 'user-1',
    type: 'payment',
    amount: 2700,
    balance_after: 12300,
    description: 'Delivery payment — Food Court',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-3',
    user_id: 'user-1',
    type: 'payment',
    amount: 500,
    balance_after: 14700,
    description: 'Delivery payment — Admin Block',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-4',
    user_id: 'user-1',
    type: 'earning',
    amount: 8500,
    balance_after: 15200,
    description: 'Courier earnings',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_COURIER_NOTIFICATIONS = [
  {
    id: 'notif-1',
    courier_id: 'user-1',
    responded: false,
    gate_only: false,
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    deliveries: {
      id: 'order-pending-1',
      order_type: 'purchase',
      pickup_location: 'Food Court',
      dropoff_location: 'Nile Hall D',
      delivery_fee: 300,
      food_cost: 2000,
      items: [{ name: 'Fried Rice + Chicken', qty: 1, price: '2000' }],
      special_instructions: 'Please add extra plantain',
    },
  },
  {
    id: 'notif-2',
    courier_id: 'user-1',
    responded: false,
    gate_only: true,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    deliveries: {
      id: 'order-pending-2',
      order_type: 'errand',
      pickup_location: 'Main Gate',
      dropoff_location: 'Library',
      delivery_fee: 500,
      food_cost: 0,
      items: [],
      special_instructions: null,
    },
  },
];

export const MOCK_ACTIVE_DELIVERY = {
  id: 'order-1',
  order_type: 'purchase',
  pickup_location: 'Food Court',
  dropoff_location: 'Nile Hall A',
  status: 'on_the_way',
  items: [{ name: 'Jollof Rice', qty: 1, price: '1500' }, { name: 'Chicken', qty: 1, price: '800' }],
  food_cost: 2300,
  delivery_fee: 300,
  service_fee: 100,
  total_amount: 2700,
  delivery_code: '4782',
  buyer_id: 'buyer-2',
  courier_id: 'user-1',
  special_instructions: null,
  payment_verified: true,
  created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
};

export const MOCK_EARNINGS = {
  today: 1800,
  this_week: 8500,
  total: 24500,
  deliveries_today: 3,
  deliveries_week: 14,
  food_reimbursed: 4600,
  tips: 500,
  withdrawn: 0,
};

export const MOCK_EARNING_HISTORY = [
  { id: 'e-1', pickup_location: 'Food Court', dropoff_location: 'Nile Hall A', delivery_fee: 300, food_cost: 2300, created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString() },
  { id: 'e-2', pickup_location: 'Female Shopping Complex', dropoff_location: 'Back Gate', delivery_fee: 400, food_cost: 0, created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString() },
  { id: 'e-3', pickup_location: 'Student Center', dropoff_location: 'Nile Hall C', delivery_fee: 300, food_cost: 1500, created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
  { id: 'e-4', pickup_location: 'Main Gate', dropoff_location: 'Sports Complex', delivery_fee: 500, food_cost: 0, created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString() },
];

export const MOCK_VENDORS = [
  {
    id: 'v-bs-chops', name: "B's Chops", zone: 'Food Court', category: 'food',
    color: 'bg-orange-500', emoji: '🍗', popular: true,
    items: [
      { name: 'Jollof Rice', price: 2100 },
      { name: 'Chinese Basmati Rice', price: 2600 },
      { name: 'White Rice + Stew', price: 2700 },
      { name: 'Boiled Yam & Egg Sauce', price: 3000 },
      { name: 'Bole & Sauce', price: 2200 },
      { name: 'Combo Loaded Fries', price: 5000 },
      { name: 'Chicken & French Fries', price: 4800 },
      { name: 'Loaded Fries', price: 4000 },
      { name: 'Sausage & French Fries', price: 3000 },
      { name: 'Irish Fries', price: 2000 },
      { name: 'Plantain Fries', price: 1500 },
      { name: 'Yam Fries', price: 1500 },
      { name: 'Loaded Large Shawarma', price: 4000 },
      { name: 'Chicken Shawarma Large + 3 Sausages', price: 3600 },
      { name: 'Chicken Shawarma Medium + 2 Sausages', price: 2900 },
      { name: 'Extra Sausage', price: 700 },
      { name: 'Pancakes / Waffles + Egg & Cocoa', price: 4000 },
      { name: 'Bole, Sauce & Fish', price: 3500 },
      { name: 'Akara & Pap', price: 2500 },
      { name: 'Pancake & Syrup', price: 2300 },
      { name: 'Waffles Plain', price: 2300 },
      { name: 'Penne Pasta Jollof', price: 3500 },
      { name: 'Continental Noodles & Egg', price: 2800 },
      { name: 'Veg Jollof Spaghetti', price: 2400 },
      { name: 'Double Chicken Burger', price: 6400 },
      { name: 'Double Beef Burger', price: 6200 },
      { name: 'Chicken Burger', price: 3200 },
      { name: 'Beef Burger', price: 3000 },
      { name: 'Chicken Sandwich', price: 2000 },
      { name: 'Peppered Grilled Chicken', price: 2000 },
      { name: 'Cole Slaw', price: 1000 },
      { name: 'Egg Sauce', price: 1000 },
      { name: 'Sausage', price: 700 },
      { name: 'Boiled Egg', price: 500 },
      { name: 'Meat Pie', price: 1200 },
      { name: 'Butter Popcorn', price: 1000 },
      { name: 'Vanilla Popcorn', price: 1000 },
      { name: 'Arizona', price: 2500 },
      { name: 'Detila Yoghurt', price: 2500 },
      { name: 'Slush (Big)', price: 1500 },
      { name: 'Monster', price: 1500 },
      { name: 'Red Bull', price: 1500 },
      { name: 'Sosa Big', price: 1500 },
      { name: 'Zobo', price: 1000 },
      { name: 'Malt', price: 800 },
      { name: 'Schweppes Can', price: 800 },
      { name: 'Fanta / Sprite', price: 600 },
      { name: 'Coke', price: 600 },
      { name: 'Water', price: 300 },
      // — unavailable —
      { name: 'Asun Jollof Rice', price: 3200, available: false },
      { name: 'Fried Rice', price: 2200, available: false },
      { name: 'White Rice & Beans', price: 3000, available: false },
      { name: 'White Rice & Fish Pepper Soup', price: 6000, available: false },
      { name: 'Loaded Large Shawarma (Beef)', price: 4000, available: false },
      { name: 'Beef Shawarma Large', price: 3500, available: false },
      { name: 'Beef Shawarma Medium', price: 2800, available: false },
      { name: 'Extra Pepper', price: 200, available: false },
      { name: 'BBQ Wings & French Fries', price: 4800, available: false },
      { name: 'Sweet Potato Fries', price: 1500, available: false },
      { name: 'Waffle Chicken Sandwich', price: 4000, available: false },
      { name: 'Chicken & Egg Salad Bowl', price: 3500, available: false },
      { name: 'Nutella Pancake', price: 3500, available: false },
      { name: 'Boiled Plantain & Egg Sauce', price: 3000, available: false },
      { name: 'Akara & Bread', price: 2500, available: false },
      { name: 'Beans Porridge', price: 1900, available: false },
      { name: 'Ewa Agoyin', price: 1900, available: false },
      { name: 'Spanish Fried Eggs', price: 1100, available: false },
      { name: 'Turkey', price: 4000, available: false },
      { name: 'Fish Slice', price: 2000, available: false },
      { name: 'Beef (Extra)', price: 1000, available: false },
      { name: 'Wings (Extra)', price: 1000, available: false },
      { name: 'Kpomo (1 Piece)', price: 500, available: false },
      { name: 'Pepper Sauce', price: 400, available: false },
      { name: 'Penne Pasta Jollof', price: 3500, available: false },
      { name: 'Spaghetti & Stew', price: 2500, available: false },
      { name: 'Stir Fry Spaghetti', price: 2400, available: false },
      { name: 'Pounded Yam & Egusi / Ogbono Soup', price: 3000, available: false },
      { name: 'Semo & Egusi Soup', price: 2500, available: false },
      { name: 'Semo & Ogbono Soup', price: 2500, available: false },
      { name: 'Semo & Afang Soup', price: 2500, available: false },
      { name: 'Eba & Afang Soup', price: 2200, available: false },
      { name: 'Garri Swallow & Egusi Soup', price: 2200, available: false },
      { name: 'Garri Swallow & Ogbono Soup', price: 2200, available: false },
      { name: 'Yamaritta', price: 2000, available: false },
      { name: 'Moi-Moi', price: 1000, available: false },
      { name: 'Subway', price: 2500, available: false },
      { name: 'Egg Tuna Sandwich', price: 2000, available: false },
      { name: 'Bubble Milk Tea (Vanilla/Coffee/Strawberry)', price: 3500, available: false },
      { name: 'Bubble Milk Tea (Chocolate)', price: 3000, available: false },
      { name: 'Milk Cake', price: 3500, available: false },
      { name: 'Chocolate Mousse Cake', price: 2500, available: false },
      { name: 'Ice Cream', price: 2700, available: false },
      { name: 'Ice Cream Cup', price: 1700, available: false },
      { name: 'Frosty Pops Popsicle', price: 3500, available: false },
      { name: 'Tropical Smoothie', price: 3000, available: false },
      { name: 'All-Flavour Milkshake', price: 2500, available: false },
      { name: 'All-Flavour Smoothie', price: 2500, available: false },
      { name: 'Prime', price: 3700, available: false },
      { name: 'Detila Yoghurt (Strawberry)', price: 2800, available: false },
      { name: 'Hollandia Yoghurt (Big)', price: 2500, available: false },
      { name: 'Chivita Exotic', price: 2500, available: false },
      { name: 'Tigernut', price: 2000, available: false },
      { name: 'Chivita Active (Drink)', price: 2000, available: false },
      { name: '5 Alive', price: 1800, available: false },
      { name: 'Fresh Pineapple Juice', price: 1800, available: false },
      { name: 'Chapman Big Cup', price: 1500, available: false },
      { name: 'Fresh Fruit Juice', price: 1500, available: false },
      { name: 'Orange / Watermelon Juice', price: 1000, available: false },
      { name: 'Chapman Small Cup', price: 1000, available: false },
      { name: 'Lady In Red', price: 1000, available: false },
      { name: 'Peach', price: 800, available: false },
      { name: 'Dudu', price: 800, available: false },
      { name: 'Predator', price: 700, available: false },
      { name: 'Teem / Plastic Schweppes', price: 600, available: false },
      { name: 'Milky Popcorn', price: 1500, available: false },
      { name: 'Small Chops', price: 1500, available: false },
      { name: 'Sausage Roll', price: 1200, available: false },
      { name: 'Super Roll', price: 1200, available: false },
      { name: 'Hot Dog Onion', price: 1200, available: false },
      { name: 'Beef Bread', price: 1200, available: false },
      { name: 'Chicken Pie', price: 1200, available: false },
      { name: 'Doughnut', price: 1000, available: false },
      { name: 'Egg Roll', price: 1000, available: false },
      { name: 'Muffins', price: 1000, available: false },
      { name: 'Sausage Finger', price: 1000, available: false },
      { name: 'Big Bread', price: 2000, available: false },
      { name: 'Cotton Candy', price: 800, available: false },
      { name: 'Small Bread', price: 700, available: false },
      { name: 'Chupa Mini', price: 400, available: false },
      { name: 'Puff Puff', price: 100, available: false },
    ],
  },
  {
    id: 'v-zulkys', name: 'Zulkys', zone: 'Food Court', category: 'food',
    color: 'bg-green-600', emoji: '🍽️', popular: true,
    items: [
      { name: 'Jollof Rice + Protein', price: 1700 },
      { name: 'Basmati Rice + Chicken', price: 1800 },
      { name: 'Ofada Rice + Sauce', price: 1500 },
      { name: 'Egusi Soup + Swallow', price: 1600 },
    ],
  },
  {
    id: 'v-jaj', name: 'JAJ Plate', zone: 'Food Court', category: 'food',
    color: 'bg-yellow-600', emoji: '🥘', popular: true,
    items: [
      { name: 'Rice + Chicken', price: 1400 },
      { name: 'Beans + Plantain', price: 900 },
      { name: 'Fried Plantain', price: 500 },
      { name: 'Yam + Egg', price: 800 },
    ],
  },
  {
    id: 'v-trayblazers', name: 'Trayblazers', zone: 'Food Court', category: 'food',
    color: 'bg-red-600', emoji: '🍱', popular: false,
    items: [
      { name: 'Rice + Chicken', price: 1500 },
      { name: 'Spaghetti + Chicken', price: 1400 },
      { name: 'Fried Rice + Fish', price: 1500 },
      { name: 'Jollof + Beef', price: 1600 },
    ],
  },
  {
    id: 'v-pizza360', name: 'Pizza 360', zone: 'Food Court', category: 'snacks',
    color: 'bg-red-500', emoji: '🍕', popular: true,
    items: [
      { name: 'Pepperoni Slice', price: 1200 },
      { name: 'Chicken Pizza Slice', price: 1300 },
      { name: 'Full Pepperoni Pizza', price: 4500 },
      { name: 'Shawarma', price: 1500 },
    ],
  },
  {
    id: 'v-cherries', name: 'Cherries', zone: 'Food Court', category: 'food',
    color: 'bg-pink-600', emoji: '🍚', popular: true,
    items: [
      { name: 'Jollof Rice & Chicken', price: 2800 },
      { name: 'Jollof Rice & Chicken & Salad', price: 3200 },
      { name: 'Jollof Rice Plain', price: 1500 },
      { name: 'Chicken Wings (Suya)', price: 2000 },
      { name: 'Beef Suya', price: 1200 },
      { name: 'Chicken Shawarma', price: 3000 },
      { name: 'Masa', price: 250 },
      { name: 'Habib Yogurt (Big Bowl)', price: 2500 },
      { name: 'Hollandia Yogurt (Big)', price: 2500 },
      { name: 'Hollandia Vanilla Yogurt', price: 2500 },
      { name: 'Habib Yogurt Cup', price: 2000 },
      { name: 'Cream Shake', price: 3000 },
      { name: 'Chivita Active', price: 2300 },
      { name: 'Pure Heaven', price: 2000 },
      { name: '5Alive', price: 1800 },
      { name: 'Smoothies', price: 1500 },
      { name: 'Zobo Freeze', price: 1500 },
      { name: 'Coffee Freeze', price: 1500 },
      { name: 'Chapman', price: 1000 },
      { name: 'Zobo Drink', price: 1000 },
      { name: 'Chivita Active (Small)', price: 700 },
      { name: 'Maltina', price: 700 },
      { name: 'Coke', price: 600 },
      { name: 'Fanta', price: 600 },
      { name: 'Sprite', price: 600 },
      { name: 'Mirinda', price: 600 },
      { name: 'Sosa', price: 500 },
      { name: 'Capri-Sun', price: 400 },
      { name: 'Water', price: 300 },
      { name: 'Mary Land Cookies', price: 2300 },
      { name: 'Groundnut', price: 1500 },
      { name: 'Meat Pie (Large)', price: 1200 },
      { name: 'Popcorn (Big)', price: 1000 },
      { name: 'Pure Bliss Milk Cookies', price: 200 },
      { name: 'Mentol Pure Fresh Gum', price: 4000 },
      { name: 'Mentol White Gum', price: 3000 },
      { name: 'Pringles (Small)', price: 2000 },
      { name: 'Chin Chin', price: 1500 },
      { name: 'Orbit Peppermint Gum', price: 1000 },
      { name: 'Hollandia Milk Big', price: 1000 },
      { name: 'Fab Biscuit', price: 600 },
      { name: 'Mentol Chewing Gum', price: 500 },
      { name: 'Coleslaw', price: 500 },
      // — unavailable —
      { name: 'Fried Rice & Chicken', price: 2800, available: false },
      { name: 'Fried Rice & Chicken & Salad', price: 3200, available: false },
      { name: 'Fried Rice & Beef', price: 2800, available: false },
      { name: 'Fried Rice Plain', price: 1500, available: false },
      { name: 'Jollof Rice & Beef & Salad', price: 3200, available: false },
      { name: 'Fried Rice & Beef & Salad', price: 3200, available: false },
      { name: 'Coconut Rice & Beef', price: 3000, available: false },
      { name: 'Coconut Rice & Chicken', price: 3000, available: false },
      { name: 'Jollof Rice & Beef', price: 2800, available: false },
      { name: 'Ofada Rice (Plain)', price: 2000, available: false },
      { name: 'Ofada Rice & Chicken with Special Sauce', price: 4500, available: false },
      { name: 'Ofada Rice with Special Sauce', price: 3000, available: false },
      { name: 'White Rice & Beef', price: 3500, available: false },
      { name: 'White Rice & Chicken', price: 3500, available: false },
      { name: 'Noodles Plain', price: 1300, available: false },
      { name: 'Noodles with Beef', price: 2500, available: false },
      { name: 'Noodles with Boiled Egg', price: 2300, available: false },
      { name: 'Noodles with Chicken', price: 2700, available: false },
      { name: 'Noodles with Egg', price: 2300, available: false },
      { name: 'Noodles with Sausage', price: 2300, available: false },
      { name: 'Ewa Agoyin with Plantain', price: 2500, available: false },
      { name: 'Fried Yam with Chicken', price: 3500, available: false },
      { name: 'Fried Yam with Egg Sauce', price: 3000, available: false },
      { name: 'Fried Yam with Peppered Sauce', price: 2800, available: false },
      { name: 'Plantain with Chicken', price: 3500, available: false },
      { name: 'Plantain with Egg Sauce', price: 3000, available: false },
      { name: 'Platter', price: 2500, available: false },
      { name: 'Beef Shawarma', price: 2000, available: false },
      { name: 'Spaghetti & Beef', price: 3000, available: false },
      { name: 'Spaghetti & Chicken', price: 3000, available: false },
      { name: 'Pounded Yam with Ewedu Soup', price: 3500, available: false },
      { name: 'Pounded Yam & Beef with Egusi', price: 3500, available: false },
      { name: 'Pounded Yam & Chicken with Egusi', price: 3500, available: false },
      { name: 'Pounded Yam with Okoro Soup', price: 3000, available: false },
      { name: 'Pounded Yam & Vegetable with Chicken', price: 3000, available: false },
      { name: 'Amala & Chicken with Ewedu Soup', price: 3000, available: false },
      { name: 'Amala Express', price: 2250, available: false },
      { name: 'Semo & Beef with Ewedu Soup', price: 3000, available: false },
      { name: 'Semo & Chicken with Ewedu Soup', price: 3000, available: false },
      { name: 'Semo with Egusi & Beef', price: 3000, available: false },
      { name: 'Semo with Egusi & Chicken', price: 3000, available: false },
      { name: 'Garri & Beef with Egusi', price: 3000, available: false },
      { name: 'Garri & Chicken with Egusi', price: 3000, available: false },
      { name: 'Garri & Beef with Ewedu Soup', price: 2700, available: false },
      { name: 'Garri & Chicken with Ewedu Soup', price: 3000, available: false },
      { name: 'Moi-Moi with Full Egg', price: 1000, available: false },
      { name: 'Moi-Moi with Half Egg', price: 800, available: false },
      { name: 'Catfish Pepper Soup', price: 2000, available: false },
      { name: 'Chips with Chicken', price: 3500, available: false },
      { name: 'Chips & Peppered Sauce', price: 3000, available: false },
      { name: 'Chips with Egg Sauce', price: 3000, available: false },
      { name: 'Pizza', price: 3500, available: false },
      { name: 'Hollandia Yogurt (Medium)', price: 1400, available: false },
      { name: 'Hollandia Yogurt (Small)', price: 900, available: false },
      { name: 'Chivita 100%', price: 2300, available: false },
      { name: 'Chivita Pineapple', price: 2300, available: false },
      { name: 'Sugarcane Juice', price: 2000, available: false },
      { name: 'Kunu Aya', price: 1500, available: false },
      { name: 'Kunu Shake', price: 1500, available: false },
      { name: 'Orange Freeze', price: 1500, available: false },
      { name: 'Fresh Fruit Juice', price: 1500, available: false },
      { name: 'Chivita Exotic (Medium)', price: 1300, available: false },
      { name: 'Virgin Mojito Drink', price: 1000, available: false },
      { name: 'Tamarind Drink', price: 800, available: false },
      { name: 'Fanta (Small)', price: 350, available: false },
      { name: 'Samosa (10 Pieces)', price: 3000, available: false },
      { name: 'Milky Doughnut', price: 1500, available: false },
      { name: 'Plantain Chips', price: 1500, available: false },
      { name: 'Fan Ice', price: 1300, available: false },
      { name: 'Meat Pie (Small)', price: 1000, available: false },
      { name: 'Sausage Roll', price: 1000, available: false },
      { name: 'Indomie Cookies', price: 1000, available: false },
      { name: 'Egg Roll', price: 800, available: false },
      { name: 'Doughnut', price: 700, available: false },
      { name: 'Kulikuli', price: 500, available: false },
      { name: 'Coconut Chips', price: 500, available: false },
      { name: 'Cookies / Crackers', price: 500, available: false },
      { name: 'Coco Mio', price: 300, available: false },
      { name: 'Samosa', price: 300, available: false },
      { name: 'Coconut Bread', price: 2500, available: false },
      { name: 'Garri, Sugar & Groundnut', price: 2500, available: false },
      { name: 'Fruit Salad', price: 2500, available: false },
      { name: 'Fried Plantain (1 Portion)', price: 2000, available: false },
      { name: 'Chocolate Short Cake', price: 2000, available: false },
      { name: 'Big Bread', price: 2000, available: false },
      { name: 'Togo Biscuit', price: 1500, available: false },
      { name: 'Vanilla Cake', price: 1500, available: false },
      { name: 'Garri with Sugar', price: 1200, available: false },
      { name: 'Mico Sticks Biscuit', price: 1200, available: false },
      { name: 'Onions Crackers', price: 1000, available: false },
      { name: 'Hollandia Milk Medium', price: 800, available: false },
      { name: 'Noreos', price: 150, available: false },
      { name: 'Alpenliebe', price: 100, available: false },
    ],
  },
  {
    id: 'v-dotcafe', name: 'Dot Cafe', zone: 'Food Court', category: 'drinks',
    color: 'bg-amber-700', emoji: '☕', popular: true,
    items: [
      { name: 'Cappuccino', price: 800 },
      { name: 'Latte', price: 900 },
      { name: 'Iced Coffee', price: 1000 },
      { name: 'Green Tea', price: 600 },
      { name: 'Smoothie', price: 1200 },
    ],
  },
  {
    id: 'v-paparims', name: 'Papa Rimz', zone: 'Food Court', category: 'food',
    color: 'bg-indigo-600', emoji: '🍔', popular: true,
    items: [
      { name: 'Singapore Rice', price: 2500 },
      { name: 'Signature Rice', price: 2500 },
      { name: 'Korean Special Rice', price: 2500 },
      { name: 'Paparimz Special Rice', price: 3000 },
      { name: 'Chicken Shawarma', price: 2500 },
      { name: 'Beef Shawarma', price: 2500 },
      { name: 'Afro Caribbean Shawarma', price: 2500 },
      { name: 'Mixed Combo Shawarma', price: 2500 },
      { name: 'Paparimz Special Shawarma', price: 3000 },
      { name: 'Spicy Chicken Pasta', price: 2500 },
      { name: 'Creamy Pasta', price: 3000 },
      { name: 'Fajita', price: 3000 },
      { name: 'Philly Cheese Steak', price: 3000 },
      { name: 'Spicy Chicken Wrap', price: 3000 },
      { name: 'Paparimz Special Wrap', price: 3000 },
      { name: 'Paparimz Special Sub', price: 3000 },
      { name: 'Chicken Burger', price: 2500 },
      { name: 'Cheese Burger', price: 2500 },
      { name: 'Mini Burger', price: 3000 },
      { name: 'Double Decker Burger', price: 3000 },
      { name: 'Paparimz Special Burger', price: 3000 },
      { name: 'Hot & Spicy Wings', price: 3500 },
      { name: 'BBQ Wings', price: 3500 },
      { name: 'Asian Wings', price: 3500 },
      { name: 'Paparimz Special Wings', price: 3500 },
      { name: 'French Fries', price: 2500 },
      { name: 'Fries & Chicken', price: 3000 },
      { name: 'Any Fries with Sauce', price: 3500 },
      { name: 'Yam Fries with Chicken', price: 4000 },
      { name: 'Yam Fries with Beef', price: 4000 },
      { name: 'Vanilla / Oreo / Strawberry Milkshake', price: 2500 },
      { name: 'Frappuccino', price: 2500 },
      { name: 'Vanilla & Chocolate Shake', price: 2500 },
      { name: 'Paparimz Special Shake', price: 2500 },
      { name: 'Water', price: 300 },
      { name: 'Zobo', price: 700 },
      { name: 'Ginger Drink', price: 800 },
    ],
  },
  {
    id: 'v-wsauce', name: 'W Sauce', zone: 'Food Court', category: 'food',
    color: 'bg-teal-600', emoji: '🌯', popular: true,
    items: [
      { name: 'Egg Fried Rice', price: 2000 },
      { name: 'Arabian Rice', price: 2500 },
      { name: 'Smoked J Rice', price: 2500 },
      { name: 'Asian Rice', price: 2500 },
      { name: 'BBQ Rice', price: 2500 },
      { name: 'Beef Rice', price: 2500 },
      { name: 'Chinese Fried Rice', price: 2500 },
      { name: 'W Special Rice', price: 2500 },
      { name: 'BBQ / Hot & Spicy Wings', price: 3500 },
      { name: 'Honey Glazed Wings', price: 3500 },
      { name: 'Korean Wings', price: 3500 },
      { name: 'Zinger Burger', price: 2500 },
      { name: 'Cheese Burger', price: 2500 },
      { name: 'San Francisco Burger', price: 2500 },
      { name: 'W Special Burger', price: 3000 },
      { name: 'Classic Chicken / Beef Shawarma', price: 2500 },
      { name: 'Mexican Chicken Shawarma', price: 2500 },
      { name: 'Spanish Chicken Shawarma', price: 2500 },
      { name: 'W Special Shawarma', price: 3000 },
      { name: 'Philadelphia Sub', price: 2500 },
      { name: 'W Special Sub', price: 3000 },
      { name: 'Plain Noodle', price: 1000 },
      { name: 'Indomie with Egg', price: 1500 },
      { name: 'Indomie with Chicken / Beef', price: 2000 },
      { name: 'W Special Noodle', price: 3000 },
      { name: 'Beef / Chicken Sandwich', price: 1500 },
      { name: 'Caribbean Chicken Sandwich', price: 2000 },
      { name: 'Yam Fries', price: 3000 },
      { name: 'French Fries', price: 2300 },
      { name: 'Extra Cheese', price: 500 },
      { name: 'Sausage', price: 400 },
      { name: 'Shredded Chicken / Beef Sauce', price: 1200 },
      { name: 'Egg / Liver / Kidney Sauce', price: 1200 },
      { name: 'Cake in a Cup', price: 1300 },
      { name: 'Chocolate / Red Velvet Cake', price: 2500 },
      { name: 'Smoothies (All Flavors)', price: 2500 },
      { name: 'Chapman / Lemonade / Virgin Mojito', price: 1000 },
      { name: 'Hibiscus (Zobo)', price: 700 },
      { name: 'Water', price: 300 },
    ],
  },
  {
    id: 'v-freenys', name: "Freenys", zone: 'Food Court', category: 'snacks',
    color: 'bg-purple-600', emoji: '🍟', popular: false,
    items: [
      { name: 'Loaded Fries', price: 1000 },
      { name: 'Chicken Strips', price: 1300 },
      { name: 'Spring Rolls (5 pcs)', price: 900 },
      { name: 'Samosa (3 pcs)', price: 600 },
    ],
  },
  {
    id: 'v-delicias', name: 'Delicias', zone: 'Female Shopping Complex', category: 'food',
    color: 'bg-rose-600', emoji: '🥗', popular: true,
    items: [
      { name: 'Grilled Chicken', price: 2000 },
      { name: 'Caesar Salad', price: 1500 },
      { name: 'Pasta Carbonara', price: 1800 },
      { name: 'Chicken Sandwich', price: 1400 },
    ],
  },
  {
    id: 'v-hatlab', name: 'Hat Lab', zone: 'Female Shopping Complex', category: 'snacks',
    color: 'bg-fuchsia-600', emoji: '🧃', popular: false,
    items: [
      { name: 'Fresh Juice (large)', price: 700 },
      { name: 'Smoothie Bowl', price: 1200 },
      { name: 'Yogurt Parfait', price: 900 },
      { name: 'Chin Chin', price: 400 },
    ],
  },
  {
    id: 'v-minimart', name: 'Mini Mart', zone: 'Female Shopping Complex', category: 'shopping',
    color: 'bg-cyan-700', emoji: '🛒', popular: false,
    items: [
      { name: 'Water (sachet x20)', price: 300 },
      { name: 'Indomie Noodles', price: 200 },
      { name: 'Bread (loaf)', price: 800 },
      { name: 'Malt Drink', price: 500 },
    ],
  },
  {
    id: 'v-bridan', name: 'Bridan', zone: 'Male Shopping Complex', category: 'shopping',
    color: 'bg-slate-600', emoji: '🏪', popular: false,
    items: [
      { name: 'Bottled Water', price: 200 },
      { name: 'Soft Drink (bottle)', price: 400 },
      { name: 'Biscuits', price: 300 },
      { name: 'Energy Drink', price: 700 },
    ],
  },
  {
    id: 'v-smoked', name: 'Smoked Restaurant', zone: 'Male Shopping Complex', category: 'food',
    color: 'bg-stone-600', emoji: '🥩', popular: true,
    items: [
      { name: 'Smoked Chicken', price: 2500 },
      { name: 'Smoked Fish + Rice', price: 2200 },
      { name: 'Suya (per stick)', price: 400 },
      { name: 'BBQ Ribs', price: 3000 },
    ],
  },
  {
    id: 'v-suya17', name: 'Suya 17', zone: 'Food Court', category: 'food',
    color: 'bg-orange-700', emoji: '🔥', popular: true,
    items: [
      { name: 'Beef / Chicken Suya', price: 600 },
      { name: 'Gas Meat', price: 2500 },
      { name: 'Balangu', price: 3000 },
      { name: 'Plain Noodles', price: 1500 },
      { name: 'Noodles with Suya', price: 2200 },
      { name: '17 Special Noodles', price: 3000 },
      { name: '17 Special Suya Loaded Fries', price: 4500 },
      { name: '17 Special Fries with Beef / Chicken', price: 4500 },
      { name: 'Agege Burger', price: 2500 },
      { name: '17 Special Philly / Fajita Sub', price: 3000 },
      { name: '17 Special Shawarma', price: 2500 },
      { name: '17 Special Wings / Suya Wings', price: 3500 },
      { name: 'Masa', price: 500 },
      { name: 'Sausage / Cheese', price: 600 },
      { name: 'Bread Buns', price: 1000 },
      { name: 'Naan Bread', price: 1500 },
      { name: 'Chips', price: 2000 },
      { name: 'Cheese Naan Bread', price: 2500 },
      { name: 'Water', price: 350 },
      { name: 'Zobo / Ginger / Tamarind', price: 700 },
      { name: 'Chapman', price: 1000 },
      { name: 'Fura', price: 1500 },
      { name: 'Slush', price: 2000 },
    ],
  },
  {
    id: 'v-yammy', name: 'Yammy', zone: 'Food Court', category: 'food',
    color: 'bg-yellow-600', emoji: '🍳', popular: false,
    items: [
      { name: 'Eggs', price: 850 },
      { name: 'Chips / Masa / Yam & Sauce', price: 2500 },
      { name: 'Meatpie', price: 900 },
      { name: 'Sausage Roll', price: 800 },
      { name: 'Samosa', price: 500 },
      { name: 'Sandwich', price: 1500 },
      { name: 'Chicken / Beef Shawarma', price: 2800 },
      { name: 'Sausage Shawarma', price: 2400 },
      { name: 'Beef / Chicken Suya', price: 600 },
      { name: 'Burger', price: 3000 },
      { name: 'Jollof & Fried Rice', price: 2000 },
      { name: 'White Rice', price: 1750 },
      { name: 'Spicy Noodles', price: 1750 },
      { name: 'Yammy Swallow', price: 1750 },
      { name: 'Pepper Meat', price: 1000 },
      { name: 'Pepper Chicken', price: 1500 },
      { name: 'Chicken Wings', price: 2750 },
      { name: 'Chicken Lap', price: 1250 },
    ],
  },
  {
    id: 'v-1129', name: '11:29 Restaurant', zone: 'Male Shopping Complex', category: 'food',
    color: 'bg-violet-600', emoji: '🕧', popular: true,
    items: [
      { name: 'Spicy Noodles (Egg)', price: 2000 },
      { name: 'Spicy Noodles (Beef / Chicken)', price: 2500 },
      { name: 'Jollof Rice', price: 2500 },
      { name: 'Naija Special Fried Rice', price: 2500 },
      { name: 'Spaghetti Bolognese', price: 3000 },
      { name: 'Rice & Beans', price: 3000 },
      { name: 'Beef Shawarma', price: 2500 },
      { name: 'Chicken Shawarma', price: 2500 },
      { name: 'Korean Fire Chicken Sub', price: 2500 },
      { name: 'Combo Shawarma', price: 2800 },
      { name: 'Philly Cheese Steak', price: 3000 },
      { name: 'Yam Fries', price: 2500 },
      { name: 'Sweet Potato Fries', price: 2500 },
      { name: 'Plantain Fries', price: 2500 },
      { name: 'Potato Wedges', price: 3000 },
      { name: 'Vanilla Milkshake', price: 2500 },
      { name: 'Oreo Lovers Shake', price: 2500 },
      { name: 'Lotus Pocus Shake', price: 2500 },
      { name: 'Strawberry Shake', price: 2500 },
      { name: 'Chocolate Shake', price: 2500 },
      { name: 'Plantain Cubes', price: 1000 },
      { name: 'Coleslaw', price: 500 },
      { name: 'Sausage', price: 500 },
      { name: 'Egg (Boiled or Fried)', price: 300 },
      { name: 'Minced Beef Sauce', price: 1200 },
      { name: 'Chicken Sauce', price: 1500 },
      { name: 'Kidney & Liver Sauce', price: 2000 },
      { name: '11:29 Wings', price: 3500 },
      { name: 'Water', price: 300 },
    ],
  },
];
