export const MOCK_USER = {
  id: 'user-1',
  email: 'imran@nileuniversity.edu.ng',
};

export const MOCK_PROFILE = {
  id: 'user-1',
  email: 'imran@nileuniversity.edu.ng',
  full_name: 'Imran Adebayo',
  phone_number: '08012345678',
  course: 'Computer Science',
  campus_status: 'resident',
  hostel: 'Nile Hall A',
  terms_accepted: true,
  onboarding_complete: true,
  is_admin: true,
  is_courier: true,
  is_blacklisted: false,
  wallet_balance: 15000,
  total_earnings: 8500,
  pro_subscriber: false,
};

export const MOCK_ORDERS = [
  {
    id: 'order-1',
    buyer_id: 'user-1',
    order_type: 'purchase',
    pickup_location: 'Food Court',
    dropoff_location: 'Nile Hall A',
    status: 'on_the_way',
    items: [{ name: 'Jollof Rice', qty: 1, price: '1500' }, { name: 'Chicken', qty: 1, price: '800' }],
    food_cost: 2300,
    delivery_fee: 300,
    service_fee: 100,
    total_amount: 2700,
    delivery_code: '4782',
    courier_name: 'Ahmed Musa',
    courier_accepted: true,
    special_instructions: null,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-2',
    buyer_id: 'user-1',
    order_type: 'errand',
    pickup_location: 'Admin Block',
    dropoff_location: 'Nile Hall B',
    status: 'delivered',
    items: [],
    item_description: 'Course registration form',
    food_cost: 0,
    delivery_fee: 400,
    service_fee: 100,
    total_amount: 500,
    delivery_code: '1234',
    courier_name: 'Fatima Ibrahim',
    courier_accepted: true,
    special_instructions: null,
    delivered_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-3',
    buyer_id: 'user-1',
    order_type: 'purchase',
    pickup_location: 'Female Shopping Complex',
    dropoff_location: 'Nile Hall C',
    status: 'placed',
    items: [{ name: 'Chicken Shawarma', qty: 2, price: '1200' }],
    food_cost: 2400,
    delivery_fee: 300,
    service_fee: 100,
    total_amount: 2800,
    delivery_code: '5619',
    courier_name: null,
    courier_accepted: false,
    special_instructions: 'Extra sauce please',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: 'tx-1',
    user_id: 'user-1',
    type: 'topup',
    amount: 20000,
    balance_after: 15000,
    description: 'Wallet top up',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-2',
    user_id: 'user-1',
    type: 'payment',
    amount: 2700,
    balance_after: 12300,
    description: 'Delivery payment — Food Court',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-3',
    user_id: 'user-1',
    type: 'payment',
    amount: 500,
    balance_after: 14700,
    description: 'Delivery payment — Admin Block',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-4',
    user_id: 'user-1',
    type: 'earning',
    amount: 8500,
    balance_after: 15200,
    description: 'Courier earnings',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_COURIER_NOTIFICATIONS = [
  {
    id: 'notif-1',
    courier_id: 'user-1',
    responded: false,
    gate_only: false,
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    deliveries: {
      id: 'order-pending-1',
      order_type: 'purchase',
      pickup_location: 'Food Court',
      dropoff_location: 'Nile Hall D',
      delivery_fee: 300,
      food_cost: 2000,
      items: [{ name: 'Fried Rice + Chicken', qty: 1, price: '2000' }],
      special_instructions: 'Please add extra plantain',
    },
  },
  {
    id: 'notif-2',
    courier_id: 'user-1',
    responded: false,
    gate_only: true,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    deliveries: {
      id: 'order-pending-2',
      order_type: 'errand',
      pickup_location: 'Main Gate',
      dropoff_location: 'Library',
      delivery_fee: 500,
      food_cost: 0,
      items: [],
      special_instructions: null,
    },
  },
];

export const MOCK_ACTIVE_DELIVERY = {
  id: 'order-1',
  order_type: 'purchase',
  pickup_location: 'Food Court',
  dropoff_location: 'Nile Hall A',
  status: 'on_the_way',
  items: [{ name: 'Jollof Rice', qty: 1, price: '1500' }, { name: 'Chicken', qty: 1, price: '800' }],
  food_cost: 2300,
  delivery_fee: 300,
  service_fee: 100,
  total_amount: 2700,
  delivery_code: '4782',
  buyer_id: 'buyer-2',
  courier_id: 'user-1',
  special_instructions: null,
  payment_verified: true,
  created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
};

export const MOCK_EARNINGS = {
  today: 1800,
  this_week: 8500,
  total: 24500,
  deliveries_today: 3,
  deliveries_week: 14,
};

export const MOCK_EARNING_HISTORY = [
  { id: 'e-1', pickup_location: 'Food Court', dropoff_location: 'Nile Hall A', delivery_fee: 300, food_cost: 2300, created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString() },
  { id: 'e-2', pickup_location: 'Female Shopping Complex', dropoff_location: 'Back Gate', delivery_fee: 400, food_cost: 0, created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString() },
  { id: 'e-3', pickup_location: 'Student Center', dropoff_location: 'Nile Hall C', delivery_fee: 300, food_cost: 1500, created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
  { id: 'e-4', pickup_location: 'Main Gate', dropoff_location: 'Sports Complex', delivery_fee: 500, food_cost: 0, created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString() },
];
